name: Docs
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/configure-pages@v3
    - uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        pip install sphinx sphinx_rtd_theme myst-parser MLTF scipy
    - name: Sphinx build
      run: |
        cd docs && make html && cd ..
    - name: Deploy
      uses: actions/upload-artifact@v2
      with:
        #path: docs/_build/html
	path: "."
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        path: docs/_build/html
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
